### ISSUE TITLE
Portable mode/version.

### ISSUE THREAD

**Issue by NEO-SPECTRUMAN** [roytam1/basilisk55#11]
what about official way of switch to portable mode?

**Comment by roytam1** [comment]
I don't have a plan to modify app code to have portable mode like what mypal/century does.

**Comment by NEO-SPECTRUMAN** [comment]
that makes it unusable for me...
i need several browsers differently configurated and portable of course 
so i've wait feodor's new browser... sad...

**Comment by roytam1** [comment]
you can use a batch to load a portable profile, just like what official versions does.

**Comment by NEO-SPECTRUMAN** [comment]
looks like it works
start basilisk.exe -Profile “Profile/”
exit
