### ISSUE TITLE
On about:profiles page, "Launch profile in new browser" buttons all launch default profile vs. selected profile

### ISSUE THREAD

**Issue by Mathwi** [roytam1/basilisk55#19]
Since at latest the 4/1 Serpent 55 release (may be older but I haven't tested older releases): on the about:profiles page, if you try to use any of the "Launch Profile in new browser" buttons, they don't launch the selected profile. They all launch the default profile instead. Thus, to switch profiles on Serpent 55 you much change the default profile, restart, then repeat the process if you want to go back to your original default profile.

The latest Serpent 52 doesn't have this bug; the "Launch Profile in new browser" buttons work correctly there.

**Comment by roytam1** [comment]
should be fixed by https://github.com/roytam1/basilisk55/commit/a01476644920cba556a83ca60968003185af55df
