### ISSUE TITLE
serpent 52 - crashing when pressing "exit customize"

### ISSUE THREAD

**Issue by NEO-SPECTRUMAN** [roytam1/basilisk55#20]
on basilisk52-g4_8 2022.04.23 there is crash when pressing "exit customize"
![2022-05-02_175708](https://user-images.githubusercontent.com/88002487/166258627-77aeaab9-3dfc-4c79-8312-135671724732.png)

the same also on latest new&clear (portable mode) 2022.04.30 

and its works on wersions before 2022.04.23

**Comment by roytam1** [comment]
https://repo.palemoon.org/MoonchildProductions/UXP/issues/1860 this one seems to be buggy, reverted in my tree.

**Comment by NEO-SPECTRUMAN** [comment]
im downgrade to basilisk52-g4.8.win32-git-20220402-f94c0da-uxp-21d56c9c9-xpmod.7z
and it works

**Comment by roytam1** [comment]
> im downgrade/downdate? to basilisk52-g4.8.win32-git-20220402-f94c0da-uxp-21d56c9c9-xpmod.7z and it works
> 
> also looks like it works on basilisk55-win32-git-20220430-cfbe5e56e-xpmod

try latest build, it should work.

**Comment by NEO-SPECTRUMAN** [comment]
looks like it works
