### ISSUE TITLE
NM28XP and Classic theme restorer

### ISSUE THREAD

**Issue by NEO-SPECTRUMAN** [roytam1/basilisk55#24]
![2022-07-03_054733_](https://user-images.githubusercontent.com/88002487/177022964-ce807f1c-212f-49ad-9964-d208d03fecf2.png)

also there is no "issues" in palemoon 27/uxp repos
also there is no palemoon 28 repo %)

**Comment by roytam1** [comment]
CTR is incompatible with NewMoon.

**Comment by NEO-SPECTRUMAN** [comment]
it compatible with firefox45 but not compatible with palemoon28? o_O

**Comment by roytam1** [comment]
Firefox 45 has new UI (i.e. Australis) which PaleMoon/NewMoon doesn't have.

**Comment by NEO-SPECTRUMAN** [comment]
ok

**Comment by NEO-SPECTRUMAN** [comment]
CTR exist from firefox 29 at lest

I tried install classic_theme_restorer-1.5.3-fx.xpi
last CTR for Firefox 29...44
and I got the same fckn blocking

**Comment by NEO-SPECTRUMAN** [comment]
also i tryed
classic_theme_restorer-1.5.0-fx.xpi
classic_theme_restorer-1.4.2-fx.xpi
classic_theme_restorer_customize_ui-1.3.2-fx.xpi (Firefox 29.0...41.0)

**Comment by NEO-SPECTRUMAN** [comment]
is it possible to disable ALL addons blocking?

**Comment by NEO-SPECTRUMAN** [comment]
maybe australias from Firefox 29...
